# Site settings
title: Fastlane
email: fastlane@krausefx.com
description: > 
  fastlane is a set of tools to make iOS app releases a blast!
  
  Instead of publishing an update of your app within days, do it with a push of a button.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://fastlane.tools"
twitter_username: KrauseFx
github_username:  KrauseFx

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
  - jemoji